### ISSUE TITLE
0.3.7 -> 0.40 broke 

### ISSUE THREAD

**Issue by jeremy-coleman** [Macil/browserify-hmr#46]
0.3.7 works fine, 0.4.0 breaks.
![image](https://user-images.githubusercontent.com/25135855/66181254-166b4380-e63e-11e9-88d1-5fc08a391ef6.png)

"start": "budo src/main.tsx -- -p [ tsify ] -p browserify-hmr -t lessify",
using this repo https://github.com/bnolan/ts-preact-boilerplate + browserify-hmr

**Comment by Macil** [comment]
Are you accessing the webpage through the filesystem, or through a local webserver? What's the origin in your URL bar?

You can pass the `--disableHostCheck` flag to browserify-hmr (`-p [ browserify-hmr --disableHostCheck ]` to get the old behavior which should work again. Note that the old behavior is vulnerable to an attack: if you visit a webpage that makes a websocket connection to http://localhost, then it can connect to browserify-hmr and read whatever file you're using browserify-hmr with.

**Comment by jeremy-coleman** [comment]
Local web server, the start command in the post above is all im doing (using budo via cli) 

Looks like thishttps://github.com/mattdesl/budo/blob/master/screenshots/terminal.png

**Comment by jeremy-coleman** [comment]
disableHostCheck fixed
